### ISSUE TITLE
data- attributes wont work

### ISSUE THREAD

**Issue by Netbioz** [pixelcog/parallax.js#101]
Here my parallax div:

```
<div data-natural-height="245" data-natural-width="1900" data-bleed="10" data-position="center bottom" data-image-src="/sites/all/themes/furcoat/images/header.jpg" data-parallax="scroll" class="breadcrumbs-region">
```

image size is 1900x245, div size is 250px, parallax is working, BUT it zoomed x2, and I can't define position or natural size by data-position="center bottom", or data-position="top" etc. It wont work as I needed. Any suggestions?

**Comment by javiertoledos** [comment]
Same here, data-position not working

**Comment by mikegreiling** [comment]
if your image is 250px tall and the parallax div is 245px tall, your image will be extremely zoomed in.  This is necessary for the parallax effect to work.  The image must be bigger than the parallax window so that there is room for it to slide... part of the image is always going to be obscured.  The exact amount of of the image that will be obscured is determined by the `speed` attribute as well as the parallax div height.

**Comment by mikegreiling** [comment]
the only time `data-position` is taken into account is when the image is taller than needed and needs to be aligned within the available space.

**Comment by Netbioz** [comment]
@mikegreiling many thanks for your answer! I will try to fix my html

**Comment by wstoettinger** [comment]
closing old issues for cleanup purposes. feel free to reopen if this issue is still relevant.
