### ISSUE TITLE
data-attributes not working with jQuery 3.1.0

### ISSUE THREAD

**Issue by wwatu** [pixelcog/parallax.js#166]
Won't work with data-attributes in jQuery 3.1.0, seems to work fine via javascript though.

**Comment by protonenfalter** [comment]
@wwatu: Does your complain refer to parallax.js not working with jQuery 3.1.0 at all (or only data handling in parallax.js)?

For me parallax.js is working smoothly with jQuery 3.1.0 after modifying registration of the event handler (last lines in parallax.js):

from:
`  $(document).on('ready.px.parallax.data-api', function () {
    $('[data-parallax="scroll"]').parallax();
  });
`

to:
`  $( function () {
    $('[data-parallax="scroll"]').parallax();
  });
`

**Comment by denbue** [comment]
Had the same issue. I (probably poorly) translated your advice into the min-version (same position) and now its working for me, too:

from:
`t(e).on("ready.px.parallax.data-api",function(){t('[data-parallax="scroll"]').parallax()})}`

to:
`t(function(){t('[data-parallax="scroll"]').parallax()})}`

**Comment by carlosnpz** [comment]
Still not working for me

**Comment by NaBiSs** [comment]
Many thanks, it solves also my issue.

**Comment by lostthetrail** [comment]
Thanks! This was useful.

**Comment by omarel1** [comment]
Same here. Looks like 2017 this bug fix still hasn't been pushed to the master

**Comment by nphilipp** [comment]
@omarel1 From the looks of it it isn't a fix, merely a workaround.

**Comment by protonenfalter** [comment]
@nphilipp Actually I think it is really a fix. The reason parallax.js stopped working with jQuery >= 3.0 is that the
`.on("ready", fn)` event handler was removed in jQuery.
See jQuery-issue here:
[https://github.com/jquery/jquery/issues/2264](url)
I am not sure if @wwatu initially had another issue with data-attributes because his report is a bit sparse, but if you are searching for a way to make parallax.js work with jQuery 3.0 and above at all, this is the way to go.

**Comment by nphilipp** [comment]
@protonenfalter Interesting, thanks for the clarification!

**Comment by nessio-de** [comment]
Still works - May 2017.
Big thanks to @protonenfalter !

**Comment by wstoettinger** [comment]
fixed with #201
