### ISSUE TITLE
Resize not working

### ISSUE THREAD

**Issue by estavex** [pixelcog/parallax.js#169]
I'm using bootstraps left navigation menu: https://startbootstrap.com/template-overviews/simple-sidebar/

The navbar pushes the page content to the right, and when I toggle collapse, the parallax background doesn't get updated (resized).

**Comment by StrangerPings** [comment]
It would be nice if it did, but because the parallax background has a fixed position so it will do that.  

A solution would be to have the navbar slide in over the content, although that doesn't solve your issue it makes the rest of the page consistent when the menu is revealed.  Also change the navbar to chnage width from 0 to 250px.

**Comment by wstoettinger** [comment]
please trigger a resize after the menu is collapsed like its stated in the readme:
```javascript
$(window).trigger('resize').trigger('scroll');
```
