### ISSUE TITLE
How to trigger recreation of mirror

### ISSUE THREAD

**Issue by arturpasevic** [pixelcog/parallax.js#194]
Is it possible to trigger recreation of parallax-mirror elements?
I my case after I delete from DOM `div.parallax-mirror` and run `$('[data-parallax="scroll"]').parallax();` again, nothing happens.

**Comment by wstoettinger** [comment]
Hey @trevorllarson! please use `$('[data-parallax="scroll"]').parallax('destroy');` instead of just deleting the mirrors, then recreation should work in case you are using data-attributes. 

When using the html version you first have to put the parallax-slider back in the parallax-window and then destroy it (this should/could be done by the library in the future).
