### ISSUE TITLE
Cannot click through to dynamic html elements within

### ISSUE THREAD

**Issue by trevorllarson** [pixelcog/parallax.js#203]
When using a block like:
```
<div class="parallax-window">
                    <div class="parallax-slider">
                        <div class="scroll-row">
                            <div class="left image">
                                <div class="contents scroll-in-object" style="background-image: url('//static.511tactical.com/cms/landing/womans-recon/callout-img-desk-3.jpg');"></div>
                            </div>
                            <div class="right call-out">
                                <div class="contents scroll-in-object">
                                    <div class="inner-contents">
                                        <div class="reticle-lockup"><img src="//static.511tactical.com/cms/landing/womans-recon/Reticle-svg.svg" alt=""></div>
                                        <h2>Carry</h2>
                                        <p>Thigh pockets on the <span class="orange">Jolie Tight</span> can easily fit larger common smart-phones to keep your hands free to enjoy the trail, gym or yoga studio.</p>
                                        <div class="cta-row">
                                            <a href="#buy-now" class="btn">Buy Now</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>`

Any of the <a> tags within are unable to be clicked. Changing the .parallax-window to an a tag itself allows the elements within to be interacted with, but breaks the parallax functionality.

**Comment by wstoettinger** [comment]
Hey @trevorllarson! This unfortunately lies in the nature of how the parallax effect is created. If you have a look at the DOM after the parallax is initialized, you will see, that the parallax-windows stays in place while the parallax-slider will be moved "behind" the content inside a "parallax-mirror" which resides in the body element. 

Now you could try `pointer-events: none;` in the css on the parallax-window and all its parents, which can be tedious, because every parent element of the parallax-window will catch the pointer events if this is not set (since v1.5.0 you can change the parallax-mirror container element to something else than the body tag, which might also help, but be careful not to break it). Or you can put your buttons/links as siblings of the parallax-slider, where they will remain in place after the parallax initialization, but unfortunately won't move with the slider.

**Comment by trevorllarson** [comment]
Hey @wstoettinger ! I appreciate the follow up!

I will say that I actually came up with an alternative option. I threw a click watcher on the parallax-window object that used a data attribute to provide the link:

`
$(".parallax-window").on("click",function(){
       var link = $(this).data('target-link');
       window.open(link,'_blank');
});
`

<div class="parallax-window" data-target-link="http://www.511tactical.com/recon-taylor-shirt.html">

Honestly worked out just fine! 

Thanks again for the follow up!

T

**Comment by wstoettinger** [comment]
good to hear you found a solution! 

looking at it I see that this converted the whole parallax window into a link. This might even work without javascript if you warp the whole thing into an &lt;a&gt; tag or even change it to an &lt;a&gt; tag and change it to `display:block`. if you have smaller buttons or several buttons/links, this gets way trickier.
