### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by avoliva** [pixelcog/parallax.js#257]
Is this project still being maintained?

**Comment by dcneuts** [comment]
Hope so, because I'm still using it!  Implemented the Alpha version, works great so far.

**Comment by wstoettinger** [comment]
yes, it is! 
I'm working on it as a side project and I try to fix all issues actually related to the source code (most issues here are because people can't read the readme or don't know how to program). 

I'm not the original author, started as a contributer to the 1.x version but I implemented the v2 from scratch myself. I'm planning to officially release v2 as soon as I have time to properly do so.

cheers!
