### ISSUE TITLE
Gray space

### ISSUE THREAD

**Issue by adamhairfield** [pixelcog/parallax.js#34]
Not sure exactly if this is an issue on my end or yours but I am getting white space on the bottom of the page in Chrome.

**Comment by mikegreiling** [comment]
The images now showing up in Safari appears to have to do with the layer ordering of the body element.  It appears in front of the .parallax-slider elements and the background attribute blocks their view.  You can set `background: transparent;` on the body or fiddle around with `z-index`.

As for the space at the bottom of the page in Chrome/Safari.  It appears to go away if you resize the window and then scroll up or down.  It would seem that the body height is being modified by another script after the parallax has been initialized (presumably by the script which is adding your twitter feed to the footer) and the calculations are thrown off until a "resize" and "scroll" event are triggered.

You can remedy this by adding the following triggers *after* the twitter feed has been loaded.
```javascript
jQuery(window).trigger('resize').trigger('scroll')
```

I think this can be done by adding the above line to **/wp-content/plugins/inline-tweets/js/handler.js** within the `success` event method.

Note: confusingly, you appear to be loading two versions of jQuery on every page load, so due to the noConflict setting, you must use `jQuery(window)` in the method call above rather than `$(window)` since the parallax plugin attaches itself to the former.

**Comment by adamhairfield** [comment]
Awesome, thanks for the help! I went ahead and added your code and it worked, but then at second thought deleted the plugin. I also cleaned up the second jquery file. Thanks a ton!

**Comment by mikegreiling** [comment]
Glad to hear it worked out!
