### ISSUE TITLE
When content of parallax expands the height of the mirror does not expand smoothly

### ISSUE THREAD

**Issue by David-Gallimore** [pixelcog/parallax.js#39]
I have a parallax with divs inside that use slideToggle.

I am mimicing the window being resized to trigger a refresh of the parallax height.

The height of the parallax changes but no way of making it smooth as it is triggered after the slideToggle has completed.

Thanks

**Comment by mikegreiling** [comment]
```javascript
jQuery(window).trigger('resize').trigger('scroll');
```

**Comment by David-Gallimore** [comment]
Hi Mike,

Thanks for your quick reply. However it did not help, I am currently doing the below:

```javascript
$(this).prev('div.wrap-infos').slideToggle(function(){
			window.dispatchEvent(new Event('resize'));
			 
});
```

Which works but the height is only changed after the divs have increased in size and so doesn't flow with the toggle slide.

Thanks

**Comment by mikegreiling** [comment]
Ah, I see.

Unfortunately there is no simple way of achieving what you want.  The plugin's 'resize' hook was meant to cover a content refresh in a single frame (e.g. when the user resizes the browser window or in response to a single, layout-changing DOM manipulation).

You could try to create a manual 'step' method for [jQuery.animate()](http://api.jquery.com/animate/#animate-properties-options) and place the trigger there, but I worry it would have pretty poor performance on older browsers since it would be recalculating every parallax element at every frame of the animation.  Let me know how it works for you if you decide to give it a try...

**Comment by wstoettinger** [comment]
closed antiquated issue for cleanup. if this is still rellevant, feel free to reopen.
