### ISSUE TITLE
Some parallax images inconsistently zoom in

### ISSUE THREAD

**Issue by expositor** [pixelcog/parallax.js#43]
Take a look at my site here:
http://trendfolio.net/apollopiano/index2.php

I've repeated the same image (and code) 5 times, but the first and last ones are the only images that display the correct zoom. The images in-between are zoomed in a little bit.

**Comment by mikegreiling** [comment]
all parallax images must be zoomed in enough to accommodate the sliding effect. Thus, part of the image must be hidden from view.

The reason parallax images at the top and bottom of the page are less zoomed is because they do not need to slide as far in one of the two directions.

**Comment by Jany-M** [comment]
I'm new to this and I am confused about the zooming as well, so I apologize for the likely-dumb following question :)
I dont understand why the images (.parallax-slider) inside .parallax-mirror progressively increase their width and height? Shouldnt the images size itself stay the same while their container adapts to the image position within the page?

**Comment by atavernor** [comment]
The left is required to keep the image horizontally centered given that it's width will have changed to maintain the aspect ratio - as as a result of the height change outlined above

**Comment by Jany-M** [comment]
Sorry but I still dont get it. Why does the width or height have to change?
I get that the `top` value has to change, depending on the parallax div position in the page, but why also the image size inside of it? what does that have to do with anything?

**Comment by atavernor** [comment]
The image height has to change in order to accommodate the parallax scroll. This is dependent on the the rate at which the parallax content is scrolling relative to the main content. You essentially need some hidden part of the image to be able to scroll into view to create the parallax effect. Without this, the parallax slider image would move up as you scroll the page and then reveal white space beneath it, remembering that the slider image is "sliding" within its div. 

Once it is accepted that the height has to be scaled, then obviously in order to maintain the correct aspect ratio, then the width must be changed proportionally. Then to achieve a reasonable user experience, the scaled image is centered using the left: position.

In our implementation, we actually found that several users were using images with either left or right biased content (such as faces) that did not benefit from the centered "cover image" approach and therefore added options to either left align or right align the scaled image as well.

**Comment by Jany-M** [comment]
Yes I understand the need to "enlarge" the image within the parallax div, otherwise of course there would be no effect at all... my confusion comes from the progressive enlargement of the images, if we use several parallax divs in one page.
In the example at http://trendfolio.net/apollopiano/index2.shouldnt each image inside the parallax div have the same size (bigger than original ok, but not bigger and bigger), no matter how many divs we use in one page?

**Comment by atavernor** [comment]
It depends upon where on the page they are and how far they have to scroll. So, images in the center of the page (vertically) will necessarily be larger than those near the top or bottom which do not have so far to move before the limits of page scroll are reached, as @mikegreiling said above, and as far as I can see is exactly what is happening on your page.

The top and bottom images only need to be enlarged sufficiently to accommodate a small amount of scroll as compared to the others which parallax over the full browser height. In practice, this would never usually be noticed by the viewer in most cases. Obviously in your example with multiples of the same image it is very evident.

**Comment by mikegreiling** [comment]
Yes as @atavernor stated the sliders at the top and bottom of the page don't need to slide as far and thus don't need to be zoomed in as much.

**Comment by mikegreiling** [comment]
This feature did not exist in some older versions.  Previously the script did not take vertical page position into account, but this more efficient use of image zoom was added after several users requested it.
