### ISSUE TITLE
Fallback for no js users

### ISSUE THREAD

**Issue by swist666** [pixelcog/parallax.js#49]
What if user don't have javascript enabled. Blank screen is not very pretty especially becouse I have white text on top of parallax box. Setting background on div under make parallax.js not working at all.

You have any solution?

**Comment by swist666** [comment]
And it's not just for users without js. People with weak internet connection may also expirience blank box.

**Comment by NeilJS** [comment]
Yes I agree. I wonder if a css background can be used - this can act as a fallback and the plugin can get the image path from the css instead of the data attribute?

**Comment by RealOrangeOne** [comment]
A nice idea, but the problem is that you couldnt control anything like than in a pure JS library, as the library wouldnt get called if JS is disabled. You could get around this by using the JS initialisation of parallaxJS however. If you set a default background image for your element in CSS, then when you init the parallax, it could change the CSS to a transparent background, and set up parallax. Although it would be nice for this to be implemented into the lib itself.

**Comment by wstoettinger** [comment]
this can already be achieved when not using data-attributes. Please refer to the readme at: https://github.com/pixelcog/parallax.js#using-inner-html-for-complex-content
