### ISSUE TITLE
Bug during scroll on Firefox and Safari

### ISSUE THREAD

**Issue by AxelBriche** [pixelcog/parallax.js#6]
Hello, I have a bug on firefox during scrolling:

I have a parallax on my newsletter section, I have set a top red border (to better observe the problem) and when I scroll to top, the image parallax move and go out of the div container (during scrolling, after it's ok).

Problem in image: http://i.imgur.com/Qo5NLbY.jpg
Normal page: http://puu.sh/bKB0q/257cc897df.jpg

Have you a solution please ?
Else in extra, it's possible to set a background from css and use parallax ?

Thanks.

**Comment by coreyward** [comment]
Yeah, this is an issue. Is there a reason that this library is creating a separate mirror of the object at the root of the body instead of using an element nested within the container (which would fix the issue)?

**Comment by mikegreiling** [comment]
I had originally developed a plugin which worked as you describe, with elements nested inside the block where the parallax effect was to take place.  However, doing so I was never able to achieve a smooth parallax effect in certain browsers like safari which would lag behind when rendering after an onscroll event.

The key advantage of placing the elements in the root of the DOM and positioning them relative to the document itself is that we can cheat and use `position:fixed` to smooth out the stuttering browsers like safari.  Now, even when the browser lazily jumps a few pixels before recalculating the parallax, the CSS attributes will ensure that the image will tend stay in place relative to the window rather than the document.

Of course this is only an advantage as long as speed is set to < 0.5 (i.e. the parallax is set to move 0.5 pixels for each 1 pixel scrolled), and looks better the lower the speed is.  At the default setting of 0.2, we're moving the parallax 1 pixel relative to the window for every 5 pixels of scroll, so the fixed position will carry the weight of up to 5 pixels of lag before the parallax will be noticeably out of place.  It's still a little jittery but it's far less so.

**Comment by coreyward** [comment]
Why not use `position: fixed` on the nested element/background?

**Comment by mikegreiling** [comment]
The fixed position is always relative to the document rather than the containing element, so IIRC I believe I'd have to correct for the position of the element on the page with a large, negative `top` attribute.  Plus I think that also would make messing with z-index attributes much harder because you'd have to take into account when parent elements are styled with `position:relative` and so on.  It has been a while since I played around with it, so my memory is fuzzy.  Perhaps it could be done that way.

**Comment by coreyward** [comment]
As long as the containing element is `position: relative` I don't believe recalculation is necessary. As far as the z-index goes, I think that should largely be left to the user — the parallax effect is about layers, and if someone is trying to achieve this effect they really ought to be thinking about how the layers of their document are arranged anyways.

**Comment by mikegreiling** [comment]
If you ever test out this method and it works out, I'd be more than happy to patch it in.

Unfortunately, I don't have the time to work on such an update right now.  My gut tells me I tried this implementation method already.  I'm at a loss to recall why I didn't embed the parallax sliding elements this way, but it seems like the way I would have tried first so I must have run into some issue with it...

Sorry that's kind of a cop out for an answer, but the plugin is serving its purpose for me just fine and I have a lot of things that are higher on my priority list ATM.

**Comment by dodlhuat** [comment]
Thanks @emaia. I switched to this plugin which is working fine! If you don't need Overlays, this plugin is working good, but as I needed them, I'll stick to the other one.

**Comment by elyrly** [comment]
I had issues with Parallax running smoothly on Safari. My solution was switching to: [Stellar JS](https://github.com/markdalgleish/stellar.js). Hopefully this help others.

**Comment by mikegreiling** [comment]
This issue appears to be at an impasse.  The OP seems to have moved on and discussion has drifted off.  I am closing this issue for now, but feel free to open a new issue if you have a specific concern.
