### ISSUE TITLE
The parallax-mirror doesn't push with main content

### ISSUE THREAD

**Issue by Genett** [pixelcog/parallax.js#74]
I use a plugin which pushes main content to show a slide menu (http://ascott1.github.io/bigSlide.js/) but the parallax-mirror doesn't push . The plugin can push more elements at the same time. When I try push the parallax-mirror element it doesn't works.

Just see a example:
http://m92002lg.bget.ru/ (click at OPEN MENU)

**Comment by jjnxpct** [comment]
Hi! I seem to have the same issue. I have an image behind a div. The container div gets 'bigger' because a have a jQuery 'slideToggle' attached to a div inside the container div. When this div slides down, the container div gets bigger, but the background image does not adapt to this new height.

Is there a way to get the parallax background image to adjust together with the slide toggle?

**Comment by juanrules** [comment]
Hello there, 
Hope this helps, it worked for me: 
I had a hero image with parallax and also a one of those Cookie messages that get hidden when clicking the 'accept' button, which was pushing the content up without updating the parallax position leaving a big white gap in consequence. 

`$( "#accept-cookie" ).on( "click", function() {  
    $('.cookieLawBar').slideToggle(function(){
        $(window).trigger('resize.px.parallax');
    });
});`

With the above, I make the parallax do the math again when the .cookieLawBar message slides up after the user clicks on the #accept-cookie button.

**Comment by ithilethiel** [comment]
Thank you @juanrules !! That fixed my problem.

**Comment by TomVDH** [comment]
Could you please elaborate? I have the same issues (with a slidable menu going up or down), adding this code with my code didn't help at all.

**Comment by wstoettinger** [comment]
please check the readme for manually refreshing.
